"""sync detection model

Revision ID: 239826a91b97
Revises: db99f928080f
Create Date: 2025-11-21 18:24:24.527021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi.testclient import TestClient

# Authorization header used in tests
AUTH = {"Authorization": "Bearer test-token"}


# revision identifiers, used by Alembic.
revision: str = '239826a91b97'
down_revision: Union[str, Sequence[str], None] = 'db99f928080f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # SQLite does not support ALTER COLUMN for type/constraint changes.
    # Comment out or remove these lines:
    # op.alter_column('alerts', 'type', ...)
    # op.alter_column('alerts', 'severity', ...)
    # op.alter_column('alerts', 'source', ...)
    # op.alter_column('alerts', 'notes', ...)
    # op.alter_column('detections', 'timestamp', ...)
    # op.alter_column('detections', 'class_name', ...)
    # op.alter_column('detections', 'confidence', ...)
    # op.alter_column('detections', 'image_path', ...)
    op.drop_index(op.f('ix_detections_id'), table_name='detections')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_detections_id'),
        'detections',
        ['id'],
        unique=False)
    op.alter_column('detections', 'image_path',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('detections', 'confidence',
                    existing_type=sa.FLOAT(),
                    nullable=False)
    op.alter_column('detections', 'class_name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('detections', 'timestamp',
                    existing_type=sa.String(),
                    type_=sa.DATETIME(),
                    nullable=False)
    op.alter_column('alerts', 'notes',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.alter_column('alerts', 'source',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('alerts', 'severity',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('alerts', 'type',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def test_alerts_list_empty(client):
    resp = client.get("/alerts/")
    assert resp.status_code == 200


def test_alerts_trigger_requires_auth(client):
    payload = {
        "detection_id": "det_unauth",
        "type": "poacher_suspected",
        "severity": "critical",
        "source": "camera_trap",
        "location": {"lat": -1.0, "lng": 36.0, "zoneLabel": "Test Zone"},
        "createdBy": "Tester",
    }
    resp = client.post("/alerts/trigger", json=payload)
    assert resp.status_code == 401


def test_alerts_trigger_success_and_list(client):
    payload = {
        "detection_id": "det_123",
        "type": "poacher_suspected",
        "severity": "critical",
        "source": "camera_trap",
        "notes": "2 individuals on foot carrying backpacks",
        "location": {
            "lat": -23.8859,
            "lng": 31.5205,
            "zoneLabel": "North Sector"},
        "createdBy": "Operator 1",
    }
    # Create alert
    resp = client.post("/alerts/trigger", headers=AUTH, json=payload)
    assert resp.status_code == 200


def test_alerts_update_status(client):
    # Create alert
    payload = {
        "detection_id": "det_to_update",
        "type": "vehicle_suspected",
        "severity": "high",
        "source": "camera_trap",
        "location": {"lat": 0.0, "lng": 0.0, "zoneLabel": "Z1"},
        "createdBy": "Updater",
    }
    resp = client.post("/alerts/trigger", headers=AUTH, json=payload)
    assert resp.status_code == 200


def test_get_alerts_empty(client: TestClient):
    """Test getting alerts when none exist"""
    response = client.get("/alerts/")
    assert response.status_code == 200
